# .github/workflows/selenium.yml
name: checkIn Automation

on:
  schedule:
    - cron: '30 1 * * 1-5'  # 每天早上 9:30 (UTC+8, 即 UTC 1:30)
    - cron: '00 11 * * 1-5'  # 每天晚上 19:00 (UTC+8, 即 UTC 11:00)
  workflow_dispatch: 

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run Selenium script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python test.py
